name: simple ML pipeline
on:
  push:
    branches:
      -main
jobs:
  test-job:
    runs-on: ubunto-Latest
    steps:
      - name: checkout code
      - uses: actions/checkout@v4
      - name: set up python 
      - uses: action/setup-python@v5
        with:
          python-version: 3.10
      - name: install dependencies
        run: |
          pip install --upgrade pip
      - name: run simple test
        run: |
          python -c "print('pipeline is working')"

